### ISSUE TITLE
Device bind screen usability suggestions

### ISSUE THREAD

**Issue by crowbarz** [nurikk/zigbee2mqtt-frontend#315]
Thank you for creating much more usable FE for z2m! After having used it for a few weeks, I had two changes I wanted to suggest to make the device bind screen more user-friendly:

1. It appears that you can only select to bind to an output cluster for the selected endpoint. This currently prevents binding to clusters that show up as input clusters, but also output as well. For example, on some of my IKEA bulbs, I can't create a binding to cluster `LColorCtrl` for the bulbs that support colour temperature. Could the UI be updated to allow binding to output clusters as well? (The list of "available" clusters in the cluster dropdown on the Reporting screen also shows input clusters only, though you can select other clusters there if you scroll down.)
2. If the device is already bound to a cluster by z2m as part of reporting setup, then that cluster appears checked in the list of binds regardless of whether the cluster is marked output or input. But as soon as it is unchecked and it is not an output cluster, the cluster disappears from the list, causing user confusion as to what has just happened. (Turns out nothing happens until you click `unbind`, and you need to first uncheck all clusters that you _don't_ want unbound.) To make it easier to unbind individual clusters, perhaps the UI could, for all bindings, list each cluster separately with an unbind button, something like this:

```
SrcEP     Destination     Cluster
  1       Coorindator     OnOff         { Unbind }
                          LevelCtrl     { Unbind }
                          LColorCtrl    { Unbind }
                          [ Clusters ]  { Bind }

[ NewEP ] [ Destination ] [ Clusters ]  { Bind }
```
where `{ }` are buttons and `[ ]` are drop-down lists.

FE version is 0.3.45

**Comment by nurikk** [comment]
in todo, but low priority

**Comment by epower53** [comment]
With the recent release of many 1000s of Inovelli VZM31-SN switches into the wild, I'm reviving this request... seems like it'd be a very useful addition.

**Comment by Impact123** [comment]
Unstale.
