### ISSUE TITLE
Custom device icon is not used in the Map tab

### ISSUE THREAD

**Issue by kajkokokoszewski** [nurikk/zigbee2mqtt-frontend#704]
### What happened
I've added an external converter for my device and changed the icon of my new device in the settings. The new icon shows in the Devices tab of the frontend but the Map tab still displays the generic Zigbee icon.

### What did you expect to happen
The icon provided in the device settings should be used in all the views in the frontend, including Map.

### How to reproduce it (minimal and precise)
Customize the icon and refresh the Map view.

### Debug info
Zigbee2MQTT version: 1.20.0

**Comment by kajkokokoszewski** [comment]
Ah, looking at the utils.ts I see why it's like that. The map view visualizes only the "bridge/response/networkmap" msg which obviously is not aware of any user's settings. But maybe the sanitizeGraph could populate the nodes with propper "definition" by looking them up based on the ieeeAddr?

**Comment by nurikk** [comment]
> Ah, looking at the utils.ts I see why it's like that. The map view visualizes only the "bridge/response/networkmap" msg which does not include the "icon" within the device definition. And that's probably due to the fact that the icon can be a dataurl and including those would make that message really big. But maybe the sanitizeGraph could add the icon to the "definition" by looking it up based on the ieeeAddr?

Hi, yes. adding definition to graph data will work. Feel free to raise a PR with changes.
