### ISSUE TITLE
Read And Expose (read-only), The database.db File In The Web GUI

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [nurikk/zigbee2mqtt-frontend#822]
**Is your feature request related to a problem? Please describe.**
This is a feature request to add and expose the database.db in the settings tab of Zigbee2MQTT frontend.

**Describe the solution you'd like**
As the popularity of custom devices, as well as the influx of TuYa devices is increasing at an exponential rate, the database.db is crucial to determining how these devices work and really assist in creating either external converters, or actual device handlers. It is quite difficult sometimes, to get a user to find these entries in their config directory (especially if using Home Assistant) so, it would be great to get this under the gui!

**Describe alternatives you've considered**
There is a decent guide on accessing the database.db entry in the Zigbee2MQTT docs, however, exposing this in the gui wouldmake things a lot easier!

**Additional context**
None

**Comment by nurikk** [comment]
Frontend is using api's exposed from zigbee2mqtt, it doesn't have any extra features. 
But having database.db exposed from api doesn't look right to me. 
What @Koenkk thinks about this?

**Comment by Koenkk** [comment]
I don't like the idea of exposing the `database.db` via the frontend, however I do like the idea of being able to create some device dump from the frontend (everything needed to add support for new devices, e.g. manufacturer name, model id, supported clusters)

**Comment by nurikk** [comment]
We already displaying all possible information in frontend
