### ISSUE TITLE
Pin routers and sensors onto house plan image?

### ISSUE THREAD

**Issue by TommySharpNZ** [nurikk/zigbee2mqtt-frontend#825]
It would be a great feature if we could upload a house plan and pin routers and sensors onto the map so they are locked to a physical location. This would make it extremely easy to see where the network might be improved by added an additional router in a certain location in the house?

**Comment by NicolaiPetri** [comment]
I vote for this feature. It would be really nice to understand network routing based on real location of devices.
Right now I can see some devices with completely random routes and it would be so much easier to see which are "weird" so I can try to fix.

**Comment by TommySharpNZ** [comment]
How do we get something like this onto the roadmap?
