### ISSUE TITLE
Can not configure reporting anymore :  'Device '0x01124b001baff38b/11' does not exist'

### ISSUE THREAD

**Issue by ALaDoffe** [nurikk/zigbee2mqtt-frontend#874]
### What happened?

It is no more possible to configure reporting for a device. 
Tried different devices.
When trying to configure,  get en error that the device does not exist.

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
debug 2021-09-27 16:09:18: Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure_reporting' with data '{"attribute":"onOff","cluster":"genOnOff","id":"0x01124b001baff38b/11","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0,"transaction":"rxg1r-2"}'
error 2021-09-27 16:09:18: Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'Device '0x01124b001baff38b/11' does not exist'
info  2021-09-27 16:09:18: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"Device '0x01124b001baff38b/11' does not exist","status":"error","transaction":"rxg1r-2"}'
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi, @Koenkk ! It seems something has been broken.

**Comment by Koenkk** [comment]
Doesn't look like a frontend bug, can you provide your data/database.db and configuration.yaml?

**Comment by ALaDoffe** [comment]
Hello

In attachment, my database.db device.yaml and [configuration.yaml.](url)
[Z2M_Conf.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7249377/Z2M_Conf.zip)

**Comment by Koenkk** [comment]
Should be fixed in the latest-dev now.

**Comment by ALaDoffe** [comment]
It is working again now.
Thank you very much

**Comment by rindlerblabla** [comment]
Have the same issue, and I have tried to update latest-dev in Docker tonight, but I still got version 1.21.1-dev commit: 738b241. Doesn't really seem to be latest version?
