### ISSUE TITLE
Notification timeout short / notification history?

### ISSUE THREAD

**Issue by psi-4ward** [nurikk/zigbee2mqtt-frontend#898]
The default notification-timeout of Notyf is 2s which is sometimes way to short to read it - especially for error messages.
Would be nice if we could increase this a bit and whould be even nicer if we have some sort of history to recap notifications (and copy out long exceptions).

Perhaps I could prepare a PR if you're interested.

**Comment by nurikk** [comment]
Notifications are comming from logs, there’s log page available in fronted p, you can see all logs there

**Comment by psi-4ward** [comment]
Okay good point!
