### ISSUE TITLE
[Bug]: Enum don't stay selected when are in Composite

### ISSUE THREAD

**Issue by Lavisx** [nurikk/zigbee2mqtt-frontend#927]
## What happened
In UI doesn't stay selected Enum components when they are in the Composite component.

## What did you expect to happen
When I select not selected value, the new value stay selected until click to Apply button.

## How to reproduce it (minimal and precise)
In definition new device in the converter use the Composite component in exposes section which contain Enum components.

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
> You can see it there https://github.com/Lavisx/lidl-valve-z2m/blob/main/lidl_radiator_valve.js And state.json is attached [state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7317461/state.json.zip)

What feature doesn't retain state, can you reduce example to the bare minimum so I can easy digest? It's quite a lot of code there.
And please attach content of `[your device] -> State`

**Comment by Lavisx** [comment]
I'm sorry. 
Problem is e.g. exposes.composite('monday', 'monday')

Device state
[device_state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7317489/device_state.json.zip)

![Snímek obrazovky 2021-10-10 v 15 21 47](https://user-images.githubusercontent.com/70548571/136697625-650f5ab8-239c-49c0-9000-35da17df757b.png)

And additional question. Is some better component for time settings and date? 
And is possible use array of values to assign to the UI e.g.
{"monday": {"part1" :{"hour": 10, "minute": 20}, "part2" :{"hour": 10, "minute": 20} },
"tuesday": {"part1" :{"hour": 10, "minute": 20}, "part2" :{"hour": 10, "minute": 20} },
...

**Comment by nurikk** [comment]
Can you hover on your problematic enum until this popup shows up? And attach screenshot here

<img width="616" alt="Screenshot 2021-10-10 at 9 34 41 PM" src="https://user-images.githubusercontent.com/1525421/136698026-3a0f0ffd-020f-4dab-89b8-6a93508fba52.png">

**Comment by Lavisx** [comment]
The problem is when the Enum is used in Composite. I select value fron Enum and the selected value is not focused.
